spring:
  application:
    name: contrats-assurance-api
  datasource:
    url: jdbc:postgresql://localhost:5432/contrats_assurance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: "ceci-est-un-secret-tres-long-a-changer-en-production-minimum-256-bits-requis"
  expiration: 86400000